### ISSUE TITLE
Filter pushdown fails for dates specified as strings

### ISSUE THREAD

**Issue by gcasto** [GoogleCloudPlatform/spark-bigquery-connector#13]
Feedback from a customer on the connector. This may be an issue with the API or the connector, unsure yet.

The connector doesn't behave as we'd expect it to when working with conditions on date types, see below. Seems that's easy to fix, please see if that can be included into next versions.The problem with date types is the following. 
If we use the following code to get necessary partitions from a partitioned table we actually get a full scan over all partitions because the condition is not pushed down: 
val df = spark.read.bigquery(TABLE).load()where(col("date_col") >= "2019-01-01")
If we transform the literal to the date type explicitly it works fine: 
val df = spark.read.bigquery(TABLE).load().where(col("date_col") >= to_date(lit("2019-01-01")))
Also it works fine if the condition is provided as an option to the reader 
val df = spark.read.bigquery(TABLE).option("filter", "data_col >= '2019-01-01'").load()

**Comment by kmjung** [comment]
This should work now.
