### ISSUE TITLE
Possibility to change grpc message size for a client

### ISSUE THREAD

**Issue by aborgatin** [GoogleCloudPlatform/spark-bigquery-connector#22]
Sometimes we got following error in this connector:

> io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Sent message larger than max (10485777 vs. 10485760)

It would be good if library client will able to change grpc message size. 
For now message size is standard - 10 * 1024 * 1024

**Comment by achelimed** [comment]
Hi,
My spark job worked fine until oct, 24 when hitting the following error:
`com.google.cloud.spark.bigquery.io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: there was an error operating on 'projects/**********/locations/us/streams/EghHYzKJHGSKHYyejoCaXIoAQ': a single table row is larger than the maximum message size`

However, there was no change neither from BQ side nor the spark job code.
Any help is appreciated.

Thanks

**Comment by coryfoo** [comment]
@kmjung I have filed an [issue](https://issuetracker.google.com/issues/143730055) in the tracker just now that has our unredacted project stream name.  Hopefully that helps you all get to the bottom of it.

**Comment by davidrabinowitz** [comment]
Fixed in 0.9.2-beta
