### ISSUE TITLE
Loading a table with regions other than US will not load.

### ISSUE THREAD

**Issue by alphacr** [GoogleCloudPlatform/spark-bigquery-connector#32]
Although loading a table from the US server will work fine, loading a table thats from outside US will return an error (Mine is currently located on `asia-east1`) that shows 

```
io.grpc.StatusRuntimeException: UNAVAILABLE: Policy checks are unavailable.
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Policy checks are unavailable.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:69)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
```

**Comment by kmjung** [comment]
The BigQuery storage API is available only in the US and EU multi-regions during the Beta period: https://cloud.google.com/bigquery/docs/reference/storage/#beta_limitations

You can expect the API to be available in all regions before GA. For asia-east1 specifically, we may be able to get something running earlier than the GA timeframe; I'll update this issue as we progress.

**Comment by alphacr** [comment]
hey kmjung, thanks so much for the reply :)) I look forward for the GA

**Comment by JD-V** [comment]
we are looking forward for this to work.
@kmjung anytime lines on when can you support reading from asia-southeast1 ?

**Comment by kmjung** [comment]
We should be able to support asia-east1 and asia-southeast1 in the next few weeks. I don't have a firm date yet, but I will update this issue when I do.

**Comment by JD-V** [comment]
Any updates on this? @kmjung

**Comment by kmjung** [comment]
The storage API is now available in asia-southeast1. See
https://cloud.google.com/bigquery/docs/reference/storage/#beta_limitations for
the full list of available regions.
