### ISSUE TITLE
Support partitioning pseudo columns

### ISSUE THREAD

**Issue by pmkc** [GoogleCloudPlatform/spark-bigquery-connector#50]
This is tricky, because AFAIK Spark has no support for pseudo columns

```
val df = spark.read.format("bigquery").option("table", TABLE) \
  .where($"_PARTITIONDATE" > "2019-01-01")
```
would require materializing _PARTITIONDATE (at least in the schema), which the BigQuery Storage API does not support.

A work around today is to use the filter option

```
val df = spark.read.format("bigquery").option("table", TABLE) \
  .option("filter", "_PARTITIONDATE > '2019-01-01'")
```

should work today

**Comment by aniket486** [comment]
@davidrabinowitz we should document this in the readme.
