### ISSUE TITLE
Can't build a jar file

### ISSUE THREAD

**Issue by sergoleksenko** [GoogleCloudPlatform/spark-bigquery-connector#59]
[INFO] --- maven-assembly-plugin:2.5.5:single (make-assembly) @ lego-cloud ---
[INFO] Failure detected.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.634 s
[INFO] Finished at: 2019-09-14T15:17:44+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (make-assembly) on project lego-cloud: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: The artifact has no valid ranges
[ERROR]   io.grpc:grpc-core:jar:1.21.0
[ERROR] 
[ERROR] Path to dependency: 
[ERROR] 	1) com.openx.lego:lego-cloud:jar:1.3-SNAPSHOT
[ERROR] 	2) com.google.cloud.spark:spark-bigquery_2.11:jar:0.8.0-beta
[ERROR] 	3) com.google.cloud:google-cloud-bigquerystorage:jar:0.98.0-beta
[ERROR] 	4) com.google.api:gax-grpc:jar:1.46.1
[ERROR] 	5) io.grpc:grpc-alts:jar:1.21.0
[ERROR] -> [Help 1]

**Comment by davidrabinowitz** [comment]
Can you please try again? I've just successfully tried a build with the com.google.cloud.spark:spark-bigquery_2.11:jar:0.8.0-beta dependency on a clean machine. Also, the problematic artifact (io.grpc:grpc-core:jar:1.21.0) seems to [exist on maven central](http://repo1.maven.org/maven2/io/grpc/grpc-core/1.21.0/).

**Comment by sergoleksenko** [comment]
Thank you for reply. Looks like it was version conflict. I added grpc-core as a dependency and it resolved the issue.
