### ISSUE TITLE
Support for catalog

### ISSUE THREAD

**Issue by ssainz** [GoogleCloudPlatform/spark-bigquery-connector#82]
Is there an API to read list of tables in a bigquery dataset (or in all datasets in a bigquery project) using the spark bigquery connector?

**Comment by davidrabinowitz** [comment]
The BigQuery API let you do that, see [listDatasets](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/bigquery/BigQuery.html#listDatasets-com.google.cloud.bigquery.BigQuery.DatasetListOption...-) and [listTables](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/bigquery/BigQuery.html#listTables-java.lang.String-com.google.cloud.bigquery.BigQuery.TableListOption...-).
