### ISSUE TITLE
unexpected EOS on DATA frame from server 

### ISSUE THREAD

**Issue by anassqasmi** [GoogleCloudPlatform/spark-bigquery-connector#84]
Hello guys, 

Will i'm trying to fetch data from BigQuery, unfortunately i'm getting this issue

For this example the table contains 34GB of data

`scala> var df = spark.read.option("parallelism", "100").bigquery("project:dataset.table")`
`scala> var size = df.rdd.mapPartitions(iter => Array(iter.size).iterator, true).collect`
`[Stage 0:===>                                                     (7 + 6) / 100`

Some stages failed with exception caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.rpc.InternalException: com.google.cloud.spark.bigquery.repackaged.io.grpc.StatusRuntimeException: INTERNAL: Received **unexpected EOS on DATA frame from server.**

Also the job takes over 10 min to compute the result, which isn't normal 

Does anybody face the same issue ?

Thank you guys

**Comment by kmjung** [comment]
This is tracked by https://issuetracker.google.com/143292803.
