### ISSUE TITLE
How to query bigquery table?

### ISSUE THREAD

**Issue by megancooper** [GoogleCloudPlatform/spark-bigquery-connector#94]
I want to perform a select inner join query on my BigQuery table and get the result. How can I do this using the connector? I know it is possible to [apply filters](https://github.com/GoogleCloudPlatform/spark-bigquery-connector#filtering-1) but my sql statement is pretty long and I don't think it'd be possible for me to do this since I also have udfs.

Is there an option I can pass, something like `query`, to do this?

**Comment by kmjung** [comment]
In concept, what you'd want to do would be to execute this query in BigQuery and then use the storage API to read the data from the results table. It looks like there's an [example](https://github.com/GoogleCloudPlatform/spark-bigquery-connector/blob/master/examples/python/query_results.py) of how to do this in our code samples; can you give that a try?

**Comment by megancooper** [comment]
Ah ok, thank you! I was hoping to be able to use the spark connector, because spark queries tend to be faster than loading in via an api and converting the results to a dataframe, but I will see how this performs! Thank you

**Comment by kmjung** [comment]
Ah, I misunderstood then. I am not a Spark expert, but I would expect that Spark would also be capable of performing such a join; however, I would not expect that doing so would require anything special from the BigQuery connector, since the shuffle / join / etc. steps would have to occur after reading the data. At best, maybe the Spark query planner could compute the filters to be passed down, assuming you're using Spark SQL. Perhaps @davidrabinowitz can help further here.

**Comment by davidrabinowitz** [comment]
There are two options:

1. Use BigQuery for the join - Run a join query on BigQuery, get the result table from the query job, and use the connector to load the data (basically what @kmjung had suggested)
2. Use spark for the join - load each table independently using the connector, and then run join on spark:
```
df1 = spark.read.format("bigquery").option("table","TABLE1").load()
df1.createOrReplaceTempView("t1")
df2 = spark.read.format("bigquery").option("table","TABLE2").load()
df2.createOrReplaceTempView("t2")
joined_df = spark,sql("select ... from t1 join t2 on ...")
```
Notice that table filters (during the read phase) cannot refer to another table, but only to a constant. For example: 

- `"int_field > 5" "date_field = CAST('2014-9-27' as DATE)"`
- `"nullable_field is not NULL"`
- `"st_equals(geo_field, st_geofromtext("POINT(2, 2)"))"`
- `"numeric_field BETWEEN 1.0 AND 5.0"`
