### ISSUE TITLE
Unsupported type 'GEOGRAPHY' when loading public dataset

### ISSUE THREAD

**Issue by stefan-matcovici** [GoogleCloudPlatform/spark-bigquery-connector#97]
When trying to load public dataset `san_francisco_bikeshare.bikeshare_station_info` an `IllegalArgumentException: Unsupported type 'GEOGRAPHY'` occurs because [here](https://github.com/GoogleCloudPlatform/spark-bigquery-connector/blob/master/src/main/scala/com/google/cloud/spark/bigquery/SchemaConverters.scala#L46) this data type isn't mapped to anything.
Nevertheless, is there any way of importing the public dataset and ignore the `GEOGRAPHY` field or add a custom mapper?

**Comment by davidrabinowitz** [comment]
As a workaround, you can select the fields you want, and leave the geography fields out.

**Comment by davidrabinowitz** [comment]
Waiting for PR #99

**Comment by davidrabinowitz** [comment]
Fixed in 0.11.0-beta
